### ISSUE TITLE
Publish current version on crates.io

### ISSUE THREAD

**Issue by vorot93** [AtherEnergy/rumqtt#51]
Crates.io version is outdated and its API does not match the documentation.

**Comment by tekjar** [comment]
I'm working on v0.11 which I'm going to push by next sunday.

**Comment by jamesmunns** [comment]
Hey, any progress on this? It looks like 0.5.0 is still the newest version on crates.io

**Comment by tekjar** [comment]
Hi @jamesmunns  @vorot93. Sorry for the delay. I've just published v0.10 to crates.io. I'm planning to implement async version of mqtt client since the current synchronous version has few drawbacks. So please note that I'm not allocating much of my bandwidth on the current architecture. Will work on this more when rust's async story is little better (help here will be awesome)

**Comment by jamesmunns** [comment]
Hey @tekjar, thanks for publishing that!

It actually is in my todo list (and a few friends of mine as well) to learn a little more about tokio. Are you planning on basing your work on tokio, or did you have something else in mind?

Where would be the best place to start? From the 0.10.0 release, the 0.11 branch, master, or somewhere else?

Also if you haven't seen docs.rs before, it might be worth switching your documentation link there to avoid some extra work: https://docs.rs/rumqtt/0.10.0/rumqtt/ or https://docs.rs/rumqtt/

Thanks again for all your work, it is very appreciated!

**Comment by tekjar** [comment]
> It actually is in my todo list (and a few friends of mine as well) to learn a little more about tokio. 

Awesome. May be we can join hands here.

> Are you planning on basing your work on tokio, or did you have something else in mind?

I already did some tokio work. I would say around 70% done. But reconnections are not easy when channels are involved because they are consumed by the eventloop. We need to write our custom `Sink` which does automatic reconnections.

> Where would be the best place to start? From the 0.10.0 release, the 0.11 branch, master, or somewhere else?

It's better to start an independent branch and use [this codec](https://github.com/tekjar/rumqttd/blob/master/src/codec.rs) that I've written for the broker. Note that I've made some changes to @inre's mqtt3 crate [here](https://github.com/tekjar/mqtt3) for using it with broker.

I personally thought it would be better to create simple echo client using tokio which does automatic reconnections by creating a custom sink. [here](https://github.com/tekjar/take-on-tokio/tree/master/echo-client)'s my work w.r.t that.

**Comment by bestouff** [comment]
In the meantime, would it be possible to have a working version on crates.io ? Or at least have some docs matching the API ?

**Comment by jamesmunns** [comment]
Hey @tekjar, would you mind pushing a `0.10.1` release with the current state of master? It would be nice to have the recent changes published :)

**Comment by tekjar** [comment]
@jamesmunns published :)

**Comment by jamesmunns** [comment]
@tekjar thanks!
